### ISSUE TITLE
How to pause/stop at specified chapter name?

### ISSUE THREAD

**Issue by erickyun** [po5/chapterskip#3]
Hi,

I have chapter named Netflix Credits 
İn place of skipping I want to know how I can pause
when the player arrives at that specified chapter name?

**Comment by po5** [comment]
Replace the `mp.set_property("time-pos", ...)` calls with a pause command. You may want to also comment out the `playlist-next` logic and replace it with a simple pause.

**Comment by erickyun** [comment]
Could you help me out 
I don't have much knowledge about lua
I tried myself but it didn't work
also can you name this lua script chapterpause so that I can seperate the two lua scripts?

https://pastebin.com/raw/2MgZSYrm
