### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by george-emerald** [po5/chapterskip#6]
Hi, I have a question regarding configuration. I'd like to skip the following chapters:
Opening
Ending
Preview
OP
ED
Recap
Endcard
Credits
Next

Since some of them are missing from the default categories I added this to my chapterskip.conf:
categories=ca>OP; cb>ED; cc>recap; cd>endcard; ce>credits; cf>next

And this to my mpv.conf:
script-opts=chapterskip-skip=opening;ending;OP;ED;preview;recap;endcard;credits;next

Yet it doesn't skip recap, next or credits. How do I fix this?

**Comment by george-emerald** [comment]
I fixed it by adding the categories to the Lua script instead.

**Comment by po5** [comment]
Editing the script is just about the worst way to "solve" your issue.
`skip` must contain your category names, e.g. `cc`.

**Comment by george-emerald** [comment]
But I tried using the category names too and it didn't work. Editing the script works.

**Comment by po5** [comment]
Because of your history of spamming useless issues on other people's repos and inability to articulate your skill issues, I am closing this.

**Comment by george-emerald** [comment]
What useless issue am I spamming in other people's issues? My most recent issues were caused for commits. What are you even talking about?

**Comment by george-emerald** [comment]
This isn't completed, why did you close it?
