### ISSUE TITLE
[HELP]: how do i skip `Next Episode Preview`

### ISSUE THREAD

**Issue by OmiChrome** [po5/chapterskip#8]
i don't know lua , so am having hard time understanding syntax  ,

here is the list of all chapter my file has 
```
00:00:00.000                    : Opening
00:01:30.023                    : Part A
00:12:33.085                    : Part B
00:21:07.266                    : Ending
00:22:47.299                    : Next Episode Preview
```
`script` skip well opening and ending , but not the 
`next episode preview` or more like `preview` 

and this is my `chapterskip.conf`
![image](https://user-images.githubusercontent.com/108952834/222512737-979e1eea-8bfe-4e99-ad38-90a090b7e653.png)

**Comment by po5** [comment]
Add your custom `previws-new` category to the list of categories to `skip`.
